### ISSUE TITLE
Nested Images are lost on update

### ISSUE THREAD

**Issue by alloyking** [whitecube/nova-flexible-content#35]
If I create a nested layout and the nested field contains an image everything will work on 'save'.
But once I update this record the images in the nested field are lost

Versions:
nova-flexible-content: 0.1.6
Nova : 2.0.3

On Save:
![image](https://user-images.githubusercontent.com/1375282/59869038-fa29ec00-9357-11e9-8bf4-b6904f259abc.png)

After Update:
![image](https://user-images.githubusercontent.com/1375282/59869136-3fe6b480-9358-11e9-8cd6-ce4436c97d6f.png)

**Comment by voidgraphics** [comment]
Thanks for reporting this, we will take a look at it soon. We'd also accept a PR that fixes this is anyone is up to it.

**Comment by atnartur** [comment]
I was trying to fix the issue in plugin's code for 3 days but I couldn't do it. 

Finally I created custom field for Nova with the following changes:
- On the backend my custom field extends from `Laravel\Nova\Fields\Image` and binds the custom Vue component for fixing frontend's behaviour.
- I created an file upload API for handling uploads directly from custom field's Vue part.
- Custom field's Vue component extends from FileField from Nova and make direct API calls to server as described above.
- At result Vue part write to FormData only filename of uploaded file. This filename is handling by nova-flexible-content as a simple text. This text simply saves to nova-flexible-content nested storage and everything goes very well.

I can share this code and also can create a pull request but I don't think this is the solution of the plugin bug. It adds the patch on the top of current architecture and don't fix the bug.

I think the problem from #29 also may be fixed with this approach.

**Comment by Nyratas** [comment]
Latest tests with `Nova v2.0.9` and `dev-master` (upcoming v0.1.8) are positive. Closed this issue since none of the cases seems to cause trouble anymore since 603e4a9.

**Comment by eboye** [comment]
Hi all,

I know this issue is resolved and yes it works when Flexible is used on model, but if used with Nova Settings it fails. This is the same issue I believe:

https://github.com/optimistdigital/nova-settings/issues/43

It just doesn't work when not in proper context?

**Comment by zeyadaverotech** [comment]
why you don't solve it since May 2019 !!

**Comment by toonvandenbos** [comment]
@zeyadaverotech _why you don't_ learn to read? _Why you don't_ try to ask politely? _Why you don't_ try by yourself first?

I'm curious if you ever had a positive response on a message like this.

Oh, and... I saw what you wrote before you edited your message. We get email notifications, you know? You must be a very frustrated person and I hope you'll get well soon, but in the meantime you should probably try another job because you clearly don't belong here. 

You're now blocked from all our repositories, congratulations! Bye.

**Comment by ameedasmah1** [comment]
is the problem still not working on Nova setting V4 !! 
Does the photo still disappear?

**Comment by thisprojectworks** [comment]
Same problem here. The problem is occurring when I use inside the Nova Settings package. If I use in a model, works well.
